title: <p style="text-align:center">Gautier Appert</p>


author: Gautier Appert


description: >
  <p style="text-align:center"><b>Research Scientist</b>
  <br><br>
  <img src="images/saumon.png" alt="hi" class="inline"/>
  <br> <br>
  <a href="https://github.com/GautierAppert">GitHub</a> - 
  <a href="https://www.linkedin.com/in/gautierappert/">LinkedIn</a> - 
  <a href="https://lichess.org/@/miaomiao">Lichess</a> 
  <br> <br> 
  gautier [dot] appert [dot] chess [at] gmail [dot] com
  <br> <br> <br> <br> <br> <br>
  </p>

theme: jekyll-theme-minimal

github:
  is_project_page: false

