title: <p style="text-align:center">Gautier Appert</p>


description: >
  <p style="text-align:center"><b>Research Scientist</b>
  <br><br>
  <br> <br>
  <a href="https://github.com/GautierAppert">GitHub</a> - 
  <a href="https://www.linkedin.com/in/gautierappert/">LinkedIn</a> - 
  <a href="https://lichess.org/@/miaomiao">Lichess</a>
  <br> <br> 
  gautier [dot] appert [dot] chess [at] gmail [dot] com
  <br> <br> <br> <br> <br> <br>
  <font size="1">Hosted on GitHub Pages &mdash; Theme by <a href="https://github.com/orderedlist">orderedlist</a></font>
  </p>

theme: jekyll-theme-minimal
